name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./mail
        file: ./mail/DOCKERFILE
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/my_email_app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      

    - name: Debug SSH Setup Before
      run: ls -la ~/.ssh || echo "No ~/.ssh directory"
      env:
        EC2_SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
    

    - name: Setup SSH for EC2
      uses: omarhosny206/setup-ssh-for-ec2@v1.0.0
      with:
        EC2_SSH_PRIVATE_KEY: $EC2_SSH_PRIVATE_KEY

    # then you can run commands/scripts directly on the EC2 instance e.g.:
    - name: Create a new file on the EC2 instance with "hello-world"
      run: ssh -o StrictHostKeyChecking=no ec2-user@100.29.45.16 "echo "hello-world" >> new_file.txt"